import type { TransactionCategory } from '@/types';

export const DEBIT_KEYWORDS: Record<string, string[]> = {
  en: ['debit', 'paid', 'charged', 'deducted', 'minus', '-'],
  hi: ['डेबिट', 'काटा गया', 'भर चुका', 'माइनस', '-', 'पाया'],
  es: ['débito', 'pagado', 'cargado', 'restado', 'menos', '-'],
  de: ['Abhebung', 'bezahlt', 'belastet', 'abgezogen', 'minus', '-'],
  fr: ['débiteur', 'payé', 'retraité', 'déduit', 'moins', '-'],
  ar: ['سحب', 'دفع', 'خصم', 'نقدا', '-', '-'],
  zh: ['支出', '已付', '扣除', '减少', '-', '-'],
  pt: ['débito', 'pagou', 'deduzido', 'menos', '-', '-'],
  sw: ['kupelewa', 'ulipiza', 'kumalizishwa', 'polewa', '-', '-'],
  id: ['debit', 'dibayar', 'dikurangkan', 'kurang', '-', '-'],
  tr: ['çıkış', 'odendi', 'deduktu', 'eksildim', '-', '-'],
  vi: ['nợ', 'đã thanh toán', 'trừ', 'giảm', '-', '-'],
  bn: ['বিদ্যমান', 'পেমেন্ট হয়েছে', 'ক্ষমতা', 'বিয়োগ', '-', '-'],
  ur: ['کھڑا', 'اپنے ادا کر دیا گیا', 'نقصان', 'کم', '-', '-'],
  ms: ['debit', 'dibayar', 'dikurangkan', 'kurang', '-', '-'],
  ko: ['채권', '지불됨', '감액', '감소', '-', '-'],
  ja: ['借入', '支払った', '差し引かれる', '減少', '-', '-'],
  ru: ['долг', 'оплачено', 'уменьшен', 'минус', '-', '-'],
  it: ['debito', 'pagato', 'dedotto', 'meno', '-', '-'],
  nl: ['debiet', 'betaald', 'afgetrokken', 'min', '-', '-'],
};

export const CREDIT_KEYWORDS: Record<string, string[]> = {
  en: ['credit', 'received', 'credited', 'added', 'plus', '+', 'deposit'],
  hi: ['เครดิต', 'प्राप्त किया', 'क्रेडिट दिया', 'लिस्ट', '+', '+'],
  es: ['crédito', 'recibido', 'acreditado', 'agregado', 'más', '+'],
  de: ['Gutschrift', 'erhalten', 'gutschrieben', 'hinzugefügt', 'plus', '+'],
  fr: ['créditeur', 'reçu', 'crédité', 'ajouté', 'plus', '+'],
  ar: ['إيداع', 'استلمت', 'تم الائتمان', 'أضف', '+', '+'],
  zh: ['收入', '已收到', '已贷记', '添加', '+', '+'],
  pt: ['crédito', 'recebeu', 'creditado', 'adicionado', 'mais', '+'],
  sw: ['kupokea', 'ulipewa', 'kuchukizwa', 'ongezeka', '+', '+'],
  id: ['kredit', 'diterima', 'ditambahkan', 'tambah', '+', '+'],
  tr: ['giriş', 'aldı', 'yazdırıldı', 'ekledi', '+', '+'],
  vi: ['nợ', 'đã nhận', 'ghi có', 'thêm', '+', '+'],
  bn: ['স্বীকার করা হয়েছে', 'লাভ', 'মুদ্রা', 'এর সাথে', '+', '+'],
  ur: ['وصول', 'ملکی', 'اعطائے گئے', 'شامل کیا گیا', '+', '+'],
  ms: ['kredit', 'terima', 'ditambahkan', 'tambah', '+', '+'],
  ko: ['채권자', '수취된', '기록됨', '추가', '+', '+'],
  ja: ['借方残高', '受領した', '加算された', '追加', '+', '+'],
  ru: ['кредит', 'получено', 'вписано', 'добавлено', '+', '+'],
  it: ['credito', 'ricevuto', 'acreditato', 'aggiunto', '+', '+'],
  nl: ['debiet', 'ontvangen', 'gecrediteerd', 'toegevoegd', '+', '+'],
};

export const CATEGORY_KEYWORDS: Record<string, Record<TransactionCategory, string[]>> = {
  en: {
    Food: ['restaurant', 'grocery', 'food', 'meal', 'cafe', 'burger', 'pizza', 'dining', 'cooking', 'snack'],
    Transport: ['fuel', 'gas', 'petrol', 'uber', 'lyft', 'taxi', 'train', 'bus', 'metro', 'aviation'],
    Shopping: ['mall', 'store', 'amazon', 'online', 'shopping', 'market', 'retail', 'outlet'],
    Entertainment: ['movie', 'theater', 'concert', 'gaming', 'streaming', 'cinema', 'hbo', 'netflix'],
    Health: ['pharmacy', 'hospital', 'doctor', 'clinic', 'medical', 'insurance', 'prescription'],
    Utilities: ['electricity', 'water', 'gas', 'internet', 'utility', 'power', 'phone'],
    Transfer: ['transfer', 'sent', 'wire', 'ach', 'zelle', 'venmo', 'paypal'],
    Salary: ['salary', 'paycheck', 'payslip', 'wage', 'commission', 'bonus'],
    Refund: ['refund', 'return', 'credit', 'reimbursed'],
    Other: ['misc', 'unknown', 'other', 'personal', 'cash'],
  },
  hi: {
    Food: ['खाना', 'रेस्तराना', 'दूध', 'भात', 'चावल', 'फल'],
    Transport: ['वॉइस', 'टैक्सी', 'ट्रेन', 'बस', 'पेट्रोल'],
    Shopping: ['शॉपिंग', 'स्टोर', 'अमेज़न', 'मॉल', 'बाजार'],
    Entertainment: ['फिल्म', 'सोनी लिव्', 'netflix', 'गेमिंग', 'कंसर्ट'],
    Health: ['दवा', 'हॉस्पिटल', 'डॉक्टर', 'क्लीनिक'],
    Utilities: ['विजला', 'पानी', 'इंटरनेट', 'बीज'],
    Transfer: ['पहुंचा', 'क्रेम', 'zelle', 'venmo'],
    Salary: ['वेतन', 'सैलरी', 'पेचेक'],
    Refund: ['वापसी', 'रिफंड', 'वापसी'],
    Other: ['अन्य', 'विचित्र', 'वैयक्तिक'],
  },
};
